/*
* Current week per date
*/
export const FETCH_CURRENT_WEEK_REFILLS_BEGIN = "FETCH_CURRENT_WEEK_REFILLS_BEGIN";
export const FETCH_CURRENT_WEEK_REFILLS_FAILURE = "FETCH_CURRENT_WEEK_REFILLS_FAILURE";
export const FETCH_CURRENT_WEEK_REFILLS_SUCCESS = "FETCH_CURRENT_WEEK_REFILLS_SUCCESS";

/*
* Current week count
*/
export const FETCH_CURRENT_WEEK_REFILLS_COUNT_BEGIN = "FETCH_CURRENT_WEEK_REFILLS_COUNT_BEGIN";
export const FETCH_CURRENT_WEEK_REFILLS_COUNT_FAILURE = "FETCH_CURRENT_WEEK_REFILLS_COUNT_FAILURE";
export const FETCH_CURRENT_WEEK_REFILLS_COUNT_SUCCESS = "FETCH_CURRENT_WEEK_REFILLS_COUNT_SUCCESS";

/*
* Current month per date
*/
export const FETCH_CURRENT_MONTH_REFILLS_BEGIN = "FETCH_CURRENT_MONTH_REFILLS_BEGIN";
export const FETCH_CURRENT_MONTH_REFILLS_FAILURE = "FETCH_CURRENT_MONTH_REFILLS_FAILURE";
export const FETCH_CURRENT_MONTH_REFILLS_SUCCESS = "FETCH_CURRENT_MONTH_REFILLS_SUCCESS";
