/*
* Current reload
*/
export const FETCH_CURRENT_RELOAD_BEGIN = "FETCH_CURRENT_RELOAD_BEGIN";
export const FETCH_CURRENT_RELOAD_FAILURE = "FETCH_CURRENT_RELOAD_FAILURE";
export const FETCH_CURRENT_RELOAD_SUCCESS = "FETCH_CURRENT_RELOAD_SUCCESS";